name: This is the workflow that always fails
on:
  push:
    branches:
      - master
        - 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    name: A failing job that creates an issue
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: always fails
      shell: bash
      run: |
        chmod +x ./ci-script.sh
        ./ci-script.sh

    - name: HandleIfFailure
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/issue-on-failure.md
