name: Discv4 Crawl and DNS Update
on:
  push:
    branches:
      - master
        - 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    name: CIStuff
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: always fails
      shell: bash
      run: |
        echo failing
        echo <<EOF
        some useful information
        
        some more useful information
        
        EOF >> .github/issue-on-failure.md
        exit 1

    - name: HandleIfFailure
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/issue-on-failure.md
