name: Golang

on:
  push:
    branches: '*'
  # Allows you to run this workflow manually from the Actions tab                                                                                                                                                                                                                                                           
  workflow_dispatch:
jobs:
  build:
    name: Go
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: General environment
      run: |
        pwd
        uname -a
        compgen -A function || true
    
    - name: Go Tools
      run: |
        which gofmt

    - name: Go Environment
      run: |
        go help environment
        go env

                                  
